Project review task week2 module1
saikatgpae/code-review pull request #1
Opened 2022-07-11 13:23 UTC by saikatgpae

This branch is created to review the project. The objective is to learn how to review a project.

2022-07-11 14:08 UTC, saikatgpae reviewed
Changes required ♻️ 

Please read my comment and change accordingly.

And request for an re-review when you complete the same.

Thanks.

2022-07-11 14:08 UTC, saikatgpae commented on index.html
> +
Please remove the unnecessary line space for a better readability.

2022-07-11 14:08 UTC, saikatgpae commented on index.html
> +    <!-- code review task -->
Please do not comment unused code. Please remove the same.

2022-07-11 14:36 UTC, youmari requested changes
Hi @saikatgpae , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter error
✔️ Great title and short summary

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-11 14:36 UTC, youmari commented on index.html
> +    <!-- code review task -->
@saikatgpae please try to explain why you require changes it may be obvious for you but not for everyone

2022-07-11 14:36 UTC, youmari commented on index.html
> +
@saikatgpae Please try to add another inline comment review in order to measure how great you are  in reviewing

2022-07-12 09:23 UTC, saikatgpae commented on index.html
> +    <!-- code review task -->
For a clean look it is better not to comment unused codes.

2022-07-12 09:25 UTC, saikatgpae commented on index.html
> +
> @saikatgpae Please try to add another inline comment review in order to measure how great you are in reviewing

Please explain a little more.

2022-07-12 10:08 UTC, ishimwezachee approved these changes
Hi @saikatgpae , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

## Optional suggestions

- [ OPTIONAL] You should implement inline comment as well. so that the student will understand where exactly is the issue.   

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-12 11:33 UTC, merged